- name: check a number is than 10
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: enter the number
    private: false
  
  tasks:
  - name: print this if number is lessthan 10
    ansible.buitin.debug:
     msg: "given number {{ my_number }} is less than 10"
    when: my_number < 10

  - name: print this if number is greater than 10
    ansible.bultin.debug:
     msg: "given number {{ my_number }}" is greater than 10"
    when: my_nymebr > 10

  