- name: Demo on Filters
  hosts: local
  connection: local
  tasks:
  - name: print default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: print uppercase
    vars:
      greeting: hello everyone
    ansible.builtin.debug:
      msg: " {{ greeting | upper }} "