- name: Demo on Filters
  hosts: local
  connection: local
  tasks:
  - name: print default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: print uppercase
    vars:
      greeting: hello everyone
    ansible.builtin.debug:
      msg: " {{ greeting | upper }} "

  - name: print unique
    vars:
      numbers: [1,2,1,3,3,45]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }} "
  
  - name: print min and max
    vars:
      numbers: [12,30,56,81,1]
    ansible.builtin.debug:
      msg: "max: {{ numbers | max }} , min: {{ numbers | min }}"