- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print the name
    ansible.builtin.debug:
      msg: " name is {{ item }} "
    loop:
      - Santhosh
      - venu
      - gopal
      - raju
      - asha