- name: loops installation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install the package
    ansible.builtin.package:
      state: present
      name: "{{ item }}"
    loop:
     - nginx
     - mysql
     - java