- name: print the variables from prompt
  hosts: web
  vars_prompt:
  - name: course
    prompt: enter the course
    private: false
  - name: duration
    prompt: enter the duration
    private: false
  tasks:
  - name: print from prompt
    ansible.builtin.debug:
     msg: "im learning {{course}} from {{duration}} days"